### ISSUE TITLE
[RFC] PHP 8 support ?

### ISSUE THREAD

**Issue by darckking** [thomasvargiu/RabbitMqModule#25]
Hello.
Are there any intentions to add a PHP 8 support ?

**Comment by thomasvargiu** [comment]
Right now I can't work on it, maybe in August or September.
Would you like to open a PR?

**Comment by darckking** [comment]
Yes, I'll work on that.

**Comment by slvrookie** [comment]
Hello.
Is there any progress on this? Ty

**Comment by darckking** [comment]
@slvrookie 
Hi,
Yes, I've opened a [PR](https://github.com/thomasvargiu/RabbitMqModule/pull/26). Awaiting for maintainer's review.
Meanwhile I already use my fork in my project.

**Comment by thomasvargiu** [comment]
A new release [5.0.0-beta1](https://github.com/thomasvargiu/RabbitMqModule/releases/tag/5.0.0-beta1) has been released.
Feedbacks will be appreciated.
